# The information of the application which delegates the swap to Forge Swap Service.
[application]
name = "Event Chain"
description = "A blockchain-based ticket-selling application that allows event hosts and participants to have full control of every ticket."

# This section contains configurations for Forge Swap service itself.
[service]
# Either http or https
schema = "http"
# The url host and port used by swap service to generate the qr_code. 
# You should make sure the wallet can reach swap service through
# this host and port.
host = "localhost"
port = 8807

# Configs the off-chain database to store swap information.
[database]
# The database type, now only supports postgres
type = "postgres"
connection = "localhost"

# This section contains the keys of assets owners for doing swapping.
# Each owner has a moniker, the application can specify which owner to use when
# creating a swap. For example, you can create an owner whose moniker is 'concert'
# to manage all concert-related assets.
# 
# [asset_owner]
#   [asset_owner.concert]
#     did = "SYSTEM:ASSET_OWNER_CONCERT_DID"
#     pk = "SYSTEM:ASSET_OWNER_CONCERT_PK"
#     sk = "SYSTEM:ASSET_OWNER_CONCERT_SK"
[asset_owners]
  [asset_owners.default]
    address = "z1ewYeWM7cLamiB6qy6mDHnzw1U5wEZCoj7"
    pk = "75CB8DA37D1FBE381AD7190ACE1C87E4D1312A689B2605F4C27A2C9E1CE63CC5"
    # The private key of the public key, base 16 encoded.
    # You can also read the secret key from environment variables like this:
    # sk = "SYSTEM:ASSET_OWNER_DEFAULT_SK"
    sk = "B4C1FED5090DD64518C20EAF5F1636CB4C2A68456A945161192635EFB83C675275CB8DA37D1FBE381AD7190ACE1C87E4D1312A689B2605F4C27A2C9E1CE63CC5"


# Config the chains that swap service shall connect to.
[chains]

  # For asset chain.
  [chains.asset]
  # The host and port to connect to the forge web
  host = "http://127.0.0.1"
  port = 8310
  # The average time(seconds) to generate a block. You should figure out this value from the chain.
  block_gap = 3

  # For application chain.
  [chains.application]
  # The host and port to connect to the forge web
  host = "http://127.0.0.1"
  port = 8410
  # The average time(seconds) to generate a block. You should figure out this value from the chain.
  block_gap = 3
